# Configurações do MySQL
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}

# Configurações do MongDB
spring.mongodb.uri=${MONGO_URI}
logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Secret Key JWT
jwt.secret=${JWT_SECRET}
server.port=${PORT:8080}